### ISSUE TITLE
引号问题

### ISSUE THREAD

**Issue by AuhNijGnahz** [TWT233/khl.py#209]
消息出现引号就会报
ValueError: No closing quotation

命令函数都进不去，直接在command里报错

**Comment by TWT233** [comment]
并不是出现引号就会报，而是引号没有闭合（没有成对的匹配引号）才会报错

command默认使用shell式的解析方法，而在shell中引号一般意味着：接下来的东西就算用空格分开了也是一个整体
在这种含义下引号未闭合就会造成解析问题：不知道哪一段是要按整体来解析

可以用regex式的解析方法，也可以捕获no closing quotation然后做相应处理：https://github.com/TWT233/khl.py/wiki/%5BFAQ%5D-handle-exceptions-during-commands
