### ISSUE TITLE
[Deprecated/弃用] PytzUsageWarning: The localize method is no longer necessary

### ISSUE THREAD

**Issue by KelsAstell** [TWT233/khl.py#214]
**Bug 描述**
在代码中引入了Botmarket刷新任务后，启动Bot出现警告，提示方法已弃用。
警告内容：
```
Python\Python38\lib\site-packages\apscheduler\util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
```

**To Reproduce**
引入以下代码:
```
@bot.task.add_interval(minutes=20)
async def botmarket_ping_task():
    api = "http://bot.gekj.net/api/v1/online.bot"
    headers = {'uuid': f"{bot_config['market_uuid']}"}
    async with aiohttp.ClientSession() as session:
        await session.post(api, headers=headers)
    Log.info(
        f'[Botmarket] 刷新了在线状态')
```

**Expected behavior**
将apscheduler更换为支持PEP 495标准的库
增加关于cron_job的教程（之前的教程很不错，辛苦了）

**Environment**
 - Python version: 3.8
 - khl.py version: Latest
 - OS: Windows Server 2016 / Windows 10 21H2

**Comment by TWT233** [comment]
apscheduler也在讨论这个问题：https://github.com/agronholm/apscheduler/discussions/570#discussioncomment-1562516

将apscheduler升级到3.9.0及以上应该能解决这个问题：https://github.com/agronholm/apscheduler/discussions/570#discussioncomment-2242511

我尝试了一下是有效的
