### ISSUE TITLE
建议: 加入类似于aiocqhttp的快速处理功能

### ISSUE THREAD

**Issue by CX4A3** [TWT233/khl.py#22]
在实际编写代码的过程中, 有部分命令会在参数错误的时候提示用户, 但是单纯使用bot.reply()方法的时候会让后续代码继续运行.
为了达到需要的效果, 往往bot.reply()方法后面跟一个return None.

建议: 参考aiocqhtto, 允许直接在return里面返回需要的操作, 类似于这样:
return {"reply": "参数输入有误!", is_temp: True}

**Comment by TWT233** [comment]
欸，是个好主意，谢谢！
我脑测了一下基础实现还是蛮简单的，拓展性也很不错，有兴趣来自己实现吗
可以在khl上加我们的服务器：https://kaihei.co/JJE0Es，有源码问题的话随时可以来问的

**Comment by CX4A3** [comment]
主要是一直没什么集中的时间 :D

**Comment by TWT233** [comment]
最近在看这个，发现其实可以直接用
```py
return await msg.reply()
```
这样的话返回的内容完全由用户控制，比较方便
