### ISSUE TITLE
api.ChannelRole.update  无法更新 role_id=0 (@全体成员)的权限

### ISSUE THREAD

**Issue by zjh4473** [TWT233/khl.py#46]
![{49A6E3EE-7BC4-C585-4454-806C3C6B819F}](https://user-images.githubusercontent.com/13052086/151730577-003262fe-25ed-46e1-a204-5bf48b8c81bf.jpg)

khl.requester.HTTPRequester.APIRequestFailed: ('POST', 'channel-role/update', {'data': {'channel_id': '6686856781955880', 'type': 'role_id', 'value': 0, 'allow': 0, 'deny': 2048}, 'headers': {'Authorization': 'Bot *'}}, 40000, '服务器角色不存在或者你没有权限操作')

我本以为是API问题，但是我手动用postman发送请求提示成功，如图所示
![89R1GH@WU7_77C%1NG)7)$Y](https://user-images.githubusercontent.com/13052086/151730639-f92c636a-4e27-46cc-a50a-482e15c59e66.png)

这是什么问题？？？？？？？？

**Comment by zjh4473** [comment]
我似乎找到原因了。
传参必须传application/json
khl.py传的是form-data 
必须传json才能100%请求成功。
我在postman 传 form-data 也提示  40000, '服务器角色不存在或者你没有权限操作')

**Comment by TWT233** [comment]
fixed in #48
