### ISSUE TITLE
ImportError: cannot import name 'Types' from 'khl.card' 

### ISSUE THREAD

**Issue by cloudyaaron** [TWT233/khl.py#52]
**Describe the bug**
ImportError: cannot import name 'Types' from 'khl.card' 

**To Reproduce**
ImportError: cannot import name 'Types' from 'khl.card' 

**Expected behavior**
should work fine

**Environment**
 - Python version:3.7.6
 - khl.py version: 0.2.3

**Comment by TWT233** [comment]
the `Types` is merged into main at #39 , which yet an unreleased pull request

for current available version(v0.2.3) card message tutorial, please refer to: https://github.com/TWT233/khl.py/blob/v0.2.3/example/ex07_card_message/ex07.py
