### ISSUE TITLE
@bot.command( rules=[Rule.is_bot_mentioned(bot)]) not triggered

### ISSUE THREAD

**Issue by cloudyaaron** [TWT233/khl.py#56]
**The following code in ex 6 dose not triggered:**

@bot.command( rules=[Rule.is_bot_mentioned(bot)])
async def world(msg: Message, mention_str: str):
    await msg.reply(f'world! I am mentioned with {mention_str}')

**Comment by TWT233** [comment]
How you invoke the command? The example should be triggered by ``/world @{Your Bot's name}``

**Comment by cloudyaaron** [comment]
No, is there a way to trigger bot reply without the /command? for example by only @bot

**Comment by TWT233** [comment]
give regex command a try:
```py
@bot.command(regex=r'^@.*?#\d+(.*)', rules=[Rule.is_bot_mentioned(bot)])
async def mention(m: Message, b: Bot, arg: str):
    await m.reply(f'somebody tagged me with "{arg}"?')
```

btw: there is a flaw in this command: you can also trigger this command by: ``@{somebody else} @{your bot}``

**Comment by cloudyaaron** [comment]
> give regex command a try:
> 
> ```python
> @bot.command(regex=r'^@.*?#\d+(.*)', rules=[Rule.is_bot_mentioned(bot)])
> async def mention(m: Message, b: Bot, arg: str):
>     await m.reply(f'somebody tagged me with "{arg}"?')
> ```
> 
> btw: there is a flaw in this command: you can also trigger this command by: `@{somebody else} @{your bot}`

Oh, haven't noticed there is a regex input, thx

**Comment by TWT233** [comment]
nvm, have a good time
