### ISSUE TITLE
请问exp05和06的readme教程是暂时下线了吗

### ISSUE THREAD

**Issue by Aewait** [TWT233/khl.py#99]
非常感谢大佬的教程，我这个没学过py的感觉都能搞定了
不过我这里没看到exp05和06的教程readme（05的有但是不完整的样子），是暂时下线了吗？

**Comment by tripleInt** [comment]
> 非常感谢大佬的教程，我这个没学过py的感觉都能搞定了 不过我这里没看到exp05和06的教程readme（05的有但是不完整的样子），是暂时下线了吗？

其实是就没有写，有时间补一下罢（

**Comment by Aewait** [comment]
> > 非常感谢大佬的教程，我这个没学过py的感觉都能搞定了 不过我这里没看到exp05和06的教程readme（05的有但是不完整的样子），是暂时下线了吗？
> 
> 其实是就没有写，有时间补一下罢（

哈哈哈，好吧

**Comment by TWT233** [comment]
嗯，写到一半摸了，愿意的话欢迎帮忙补一个
